#is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
#    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

set -g default-terminal "xterm"
#set -g default-terminal "xterm-256color"
#set -g default-terminal "screen-256color"

set -g mouse on        #For tmux version 2.1 and up
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Cofig

# Status Bar
set-option -g status-interval 1
set-option -g status-left ''
set-option -g status-right '%l:%M%p'
set-option -g status-bg colour236
set-option -g status-fg colour48
set-option -g pane-active-border-fg colour31
set-option -g pane-border-fg colour31

# window
#set-window-option -g window-status-current-fg magenta
set-window-option -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R# Set window notifications

setw -g monitor-activity on
set -g visual-activity on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g status-right "CPU:#{cpu_percentage} | Batt: #{battery_percentage} #{battery_icon} #{battery_remain}"

# Restoring vim sessions
set -g @resurrect-strategy-vim 'session'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'

