color = ""

[default]
  account_id = "acct_1KIdQkCOSTCQz11F"
  device_name = "Ricardos-MacBook-Pro.local"
  display_name = "Sponsowrd.me"
  live_mode_api_key = "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"
  live_mode_publishable_key = "pk_live_51KIdQkCOSTCQz11FfOPvUpTh1qEK1OT4a7YOH6O68q7o78IGGJMR9Se5htdTR2wMsWUOjGoGeXw5u5Zaw79kgY9S00LSiSGlQ3"
  test_mode_api_key = "rk_test_51KIdQkCOSTCQz11FTF46ZT5arCvtDFW2bTw8LDjY8gBzQhLkiatgwiRRtCso0ejHuY7TSuqychf0xdd6Pqfpy4L900yCqjrDO0"
  test_mode_publishable_key = "pk_test_51KIdQkCOSTCQz11FbvnA0o9JG79MOgCUz4sHDjtDMbI9dQIHlgXwZSqnpujtD7oggQ7f84lf2eD4fUshNzLPdXvj00zabQ2t1a"
